# 이 방식은 현재 docker-compose.yaml에서 도커 내부의 MySQL을 생성하는 방식이다.
# 그래서 Mac에 설치된 MySQL과는 완전히 별개로 동작하고 있다.
# 즉, docker exec -it mysql mysql -u root -p로 들어가는 것과 mysql -u root -p로 들어가는 것 두개가 다른 서버로 이루어지고 있다.
# 그래서 한쪽에서 database를 생성해도 두개가 공유되지 않고, 서로 다른 mysql을 쓰고 있어서 다르게 동작한다!

# 아래 방식은 docker-compose.yaml에서 도커 내부의 MySQL을 생성하는 방식
version: "3"
services:
  app:
    image: your-app-image  # 실제 사용할 애플리케이션 이미지
    container_name: my_app
    depends_on:
      - db
    environment:
      - DB_HOST=host.docker.internal  # Mac에 설치된 MySQL 사용
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1123
      - DB_NAME=mydb

  db:
    image: mysql:8.4  # <-- ❌ 이 부분을 삭제하거나 코멘트 처리 가능
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=1123
      - TZ=Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
